catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contact, IndexListView, ProductListView, ProductDetailView, BlogCreateView, BlogListView, \
    BlogDetailView, BlogUpdateView, toggle_activity, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    BlogDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('contact/', contact, name='contact'),
    path('product/', ProductListView.as_view(), name='product_list'),
    path('view<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_view'),
    path('product/create/', ProductCreateView.as_view(), name='create_product'),
    # path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),

    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),

    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование', unique=True)
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.CharField(max_length=150, verbose_name='категория')
    purchase_price = models.IntegerField(verbose_name='цена за покупку')
    date_of_creation = models.DateTimeField(auto_now_add=True)
    last_modified_date = models.DateTimeField(auto_now=True)

    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    anonymous_users = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='анонимный пользователь')

    is_published = models.BooleanField(default=False, verbose_name='признак публикации')

    def __str__(self):
        return f'{self.name} {self.purchase_price} {self.category}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', null=True)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'


class Possibilities(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'возможность'
        verbose_name_plural = 'возможности'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.TextField(verbose_name='номер версии')
    name_version = models.CharField(max_length=50, verbose_name='название версии', unique=True)
    indicator = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.version_number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версия'

catalog/forms.py
from django import forms
from catalog.models import Product, Possibilities, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        # fields = '__all__'
        # fields = ('name', )
        exclude = ('anonymous_users',)


    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        exception = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', ]
        if cleaned_data in exception:
            raise forms.ValidationError('Запрещенный продукт')

        return cleaned_data

class PossibilitiesForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Possibilities
        fields = '__all__'


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from catalog.forms import ProductForm, PossibilitiesForm, VersionForm
from catalog.models import Product, Blog, Possibilities, Version

from django.urls import reverse

from catalog.services import get_catalog_cache


class IndexListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/index.html'

@login_required
@permission_required('catalog.view_product')
def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')

    context = {
        'title': 'Контакт'
    }
    return render(request, 'catalog/contact.html', context)


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/product.html'


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    permission_required = 'catalog.view_product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['possibilities'] = get_catalog_cache(self)
        return context_data

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.delete_product'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.crate_product'
    success_url = reverse_lazy('catalog:index')

    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    #success_url = reverse_lazy('catalog:index')

    def get_success_url(self):
        return reverse('catalog:update_product', args=[self.kwargs.get('pk')])
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

#####

class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('catalog:blog_list')


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('catalog:blog_list')


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

@login_required
def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_active:
        blog_item.is_active = False
    else:
        blog_item.is_active = True

    blog_item.save()

    return redirect(reverse('catalog:index'))

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}" type="button"
                       class="btn btn-outline-info">Профиль</a>
                    <a href="{% url 'users:logout' %}" type="button"
                       class="btn btn-outline-info">Выйти</a>
                    {% else %}
                    <a href="{% url 'users:login' %}" type="button"
                       class="btn btn-outline-info">Войти</a>
                    <a href="{% url 'users:register' %}" type="button"
                       class="btn btn-outline-info">Регистрация</a>
                    {% endif %}
                </div>
                {% include 'catalog/includes/inc_catalog_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Мystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contact/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/product/">Продукты</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Отзывы</a>

    </nav>
</div>

{% block content %}
{% endblock %}
</div>
</div>
</div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'catalog:index' %}">Вернуться на главную</a>
        </p>
        <p>&copy;2023 - {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-da">
                        Подтверждение
                        </button>
                        <a href="{% 'catalog:blog_list' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"
                         src="/media/{{ object.image }}"
                         alt="Card image cap">
                    <div class="card-header">
                        <h3 class="card-title">
                            Блог "{{ object.title }}"
                        </h3>
                    </div>
                    <div class="card-body">

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="card-body">
                                <p>
                                    {{ object.body }}
                                </p>
                                <div class="card-footer">
                                    Просмотры: {{ object.views_count }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</main>


{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Написать отзыв</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object|title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:blog_view' object.pk %}" type="button"
                       class="btn btn-success">Читать</a>
                    <a href="{% url 'catalog:blog_edit' object.pk %}" type="button"
                       class="btn btn-warning">Редактировать</a>
                </div>
                <a href="{% url 'catalog:blog_delete' object.pk %}" type="button"
                       class="btn btn-danger">Удалить</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Наши контакты</h1>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>77-77777777</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>г. Санкт-Петербург, ул. Гороховая дом 1</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Контактный телефон" required></textarea>
                            </div>
                            <div class="mb-3">
                                <input type="submit">
                                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    MyStore
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        {% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Мystore</h1>
    <p class="lead">Мystore - отличный магазин</p>
</div>

<div class="container">
    <div class="col-12 mb-5">
        {% if perms.catalog.create_product %}
        <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
        {% endif %}
    </div>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="/media/{{ object.image }}"
                     alt="Card image cap">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.name }}</h1>
                    {% if perms.catalog.view_product %}
                    <a href="{% url 'catalog:product_view' object.pk %}" type="button"
                       class="btn btn-outline-info">Посмотреть</a>
                    {% endif %}
                    {% if perms.catalog.change_product %}
                    <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                       class="btn btn-outline-success">Изменить</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                       class="btn btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                МуStore
                <small class="d-block mb-3 text-muted"></small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/blog/">О нас пишут отзывы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="/contact/">Контакты</a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    {% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Наши продукты</h1>


    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"

                         src="{{ object.image|mediapath }}"
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object|title }}</p>
                        <h1 class="text-muted">{{ object.anonymous_users|default:"Обычный" }}</h1>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'catalog:product_view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                <a href="{% url 'catalog:create_product' %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                            </div>
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

</main>


{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-danger">
                        Подтверждение
                        </button>
                        <a href="{% url 'catalog:index' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
       <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"
                         src="/media/{{ object.image }}"
                         alt="Card image cap">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.category }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Наименование</td>
                                <td>{{ object.name }}</td>
                            </tr>
                            <tr>
                                <td>Описание</td>
                                <td>{{ object.description }}</td>
                            </tr>
                            <tr>
                                <td>Цена за покупку</td>
                                <td>{{ object.purchase_price }}</td>
                            </tr>
                        </table>
                        <div class="card-footer">
                            Просмотры: {{ object.views_count }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h3 class='card-title'>
                            Возможность {{object.description}}
                        </h3>
                    </div>
                    <div class="card-body">
                        <ul>
                            {% for possib in possibilities%}
                            <li>{{ possib }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</main>
{% endblock %}